# Generated by Django 4.2 on 2023-05-13 20:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='calculation_end_dttm',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='calculation_start_dttm',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='create_dttm',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 23, 3, 30, 902807)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReportRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('is_paraphrase', models.BooleanField()),
                ('probability', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.report')),
            ],
        ),
    ]
