# Generated by Django 4.2 on 2023-05-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_calculation_end_dttm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='model_version',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
