# Generated by Django 4.2 on 2023-05-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_model_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrecognition',
            name='sentence_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
